# Generated by Django 3.2.5 on 2021-07-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210706_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_code',
            field=models.CharField(default='', max_length=6),
        ),
    ]
