# Generated by Django 3.2.5 on 2021-07-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_lecture_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='year',
            field=models.CharField(choices=[('FIRST', 'FIRST'), ('SECOND', 'SECOND'), ('THIRD', 'THIRD'), ('FOURTH', 'FOURTH')], default='FIRST', max_length=8),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='year',
            field=models.CharField(choices=[('FIRST', 'FIRST'), ('SECOND', 'SECOND'), ('THIRD', 'THIRD'), ('FOURTH', 'FOURTH')], default='FIRST', max_length=8),
        ),
    ]
